### ISSUE TITLE
SoftRF show its own deviceID as traffic

### ISSUE THREAD

**Issue by 8lazo8** [lyusupov/SoftRF#76] opened 2020-01-09 17:25 UTC
## Hardware

- [ ]   Standalone
- [x]   Prime Mark II
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

![IMG_20200109_171300](https://user-images.githubusercontent.com/17548378/72089009-8e1acf80-330b-11ea-9b2e-eb78ff757acc.jpg)

## Firmware version

![Screenshot_2020-01-09-17-41-51-117_com android browser](https://user-images.githubusercontent.com/17548378/72088553-b2c27780-330a-11ea-9835-9c86d747a00a.jpg)

## Firmware settings

![Screenshot_2020-01-09-17-42-00-724_com android browser](https://user-images.githubusercontent.com/17548378/72088590-cbcb2880-330a-11ea-9864-e765d2f69e20.jpg)

## Describe the bug (or ask a question)

I am a new SoftRF user, today I went out for a test on the ground.
Next week I plan to make an in flight test.

When the Prime MKII is near to an aircraft - 2-300 meters or closer - equiped with OGN tracker periodically it seems to "receive" its own tracker ID as foreign tracker and it is listed as traffic in the Skyview and in xcsoar as well.  The phenomenon is intermittent.
It tested this with two different aircrafts.

After the aircrafts departured the "self reflection" disappeared only the real aircraft was seen on the screen.

## To Reproduce

Te be close to an OGN tracker equipped aircraft, maximum 2-300 meters.

## Expected behavior

To receive/display only the foreign aircraft deviceID but not itself.

**Comment by Ben64Smith** [comment] 2020-01-09 17:30
From memory I think paweł added rebroadcast functionality in the later versions of the OGN tracker, this is probably the cause of your issue.

**Comment by 8lazo8** [comment] 2020-01-09 17:36
> 
> 
> From memory I think paweł added rebroadcast functionality in the later versions of the OGN tracker, this is probably the cause of your issue.

This means that the foreign aircraft rebroadcasted my deviceID?  I am pretty sure it was not SoftRF device inside.

Does this rebroadcast function has anything to do to proximity of the trackers? So its not active on larger distances? I mean I should have to receive it all the time. And it also would cause alerts.
Or in this case the self deviceID should be filtered?

**Comment by lyusupov** [comment] 2020-01-09 17:44
@Ben64Smith 
Correct. I also expect that this likely happens due to re-broadcast feature of OGN tracker.
I don't remember if I have seen this with my build of STM32 OGN tracker on a breadboard.
It probably depends on particular revision of OGN firmware, settings and certain conditions to be met.

@8lazo8 
Could you connect your Prime Mk2 to a PC and **capture a NMEA log on 38400,8*N1** ? 
If the is a 'ghosting traffic' - we will likely see it in a PFLAA sentence.

**Comment by 8lazo8** [comment] 2020-01-09 18:03
> 
> 
> @Ben64Smith
> Correct. I also expect that this likely happens due to re-broadcast feature of OGN tracker.
> I don't remember if I had seen this with my build of STM32 OGN tracker on a breadboard.
> It probably depends on particular revision of OGN firmware, settings and certain conditions has to be met.
> 
> @8lazo8
> Could you connect your Prime Mk2 to a PC and **capture a NMEA log on 38400,8*N1** ?
> If there is a 'ghosting traffic' - we will likely see it in a PFLAA sentence.

Yes I can do that. You need the capture when "ghosting" can be seen on the screen?

I have two Mk2-s but between them this never happened. To reproduce the phenomenon I will need to go for another field trip.
I will capture the log ASAP whichever is needed.

**Comment by lyusupov** [comment] 2020-01-09 18:22
No rush. Take it when able. ZIP , then drag and drop here.

> You need the capture when "ghosting" can be seen on the screen?

Yes.

**Comment by 8lazo8** [comment] 2020-01-11 14:58
> 
> 
> No rush. Take it when able. ZIP , then drag and drop here.
> 
> > You need the capture when "ghosting" can be seen on the screen?
> 
> Yes.

Hi,
Today I managed to collect logs.  After all I could not take it from the serial but I hope xcsoar NMEA dump will be good as well. 
There were lots of "ghostings".
[2020-01-11_10-53.zip](https://github.com/lyusupov/SoftRF/files/4049437/2020-01-11_10-53.zip)

**Comment by lyusupov** [comment] 2020-01-11 15:07
Thanks!

I've committed https://github.com/lyusupov/SoftRF/commit/b0ddbac7e7af06a9929581df677d2e3aefa4477a and https://github.com/lyusupov/SoftRF/commit/6e4e9bb6ee95fe397c8b22baf141dc555ef2e9b2

[Build](https://github.com/lyusupov/SoftRF/tree/master/software/firmware/source#esp32) and update your **Prime MkII**(s).

Those 2 commits above should fix this issue. Please, test and confirm.

**Comment by 8lazo8** [comment] 2020-01-11 18:36
> 
> 
> Thanks!
> 
> I've committed [b0ddbac](https://github.com/lyusupov/SoftRF/commit/b0ddbac7e7af06a9929581df677d2e3aefa4477a) and [6e4e9bb](https://github.com/lyusupov/SoftRF/commit/6e4e9bb6ee95fe397c8b22baf141dc555ef2e9b2)
> 
> [Build](https://github.com/lyusupov/SoftRF/tree/master/software/firmware/source#esp32) and update your **Prime MkII**(s).
> 
> Those 2 commits above should fix this issue. Please, test and confirm.

Update has been done, will test it soon.

**Comment by 8lazo8** [comment] 2020-01-17 10:26
There is IMC in the area since a week, hopefully next week it will good enough for a test.

**Comment by lyusupov** [comment] 2020-01-27 06:06
**Resolution:** fixed in https://github.com/lyusupov/SoftRF/commit/b0ddbac7e7af06a9929581df677d2e3aefa4477a and https://github.com/lyusupov/SoftRF/commit/6e4e9bb6ee95fe397c8b22baf141dc555ef2e9b2

**Closed by lyusupov** 2020-01-27 06:06 UTC
Labels: bug
